baseURL = "http://daikw.github.io/"
languageCode = "en-us"
title = "daikw as a yak-shaver"
theme = "almeida-cv"

[params]
  colorDark = "#666"
  colorLight = "#fff"
  colorPageBackground = "#ddd"
  colorPrimary = "#e3bfb8"
  colorPrimaryText = "#fff"
  colorRightColumnBackground = "#f5f5f5"
  colorSecondary = "#aaa"
  pages = 1

